name: matterchat-dev
services:
  postgres:
    image: postgres:18-alpine
    container_name: matterchat-dev-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:8-alpine
    container_name: matterchat-dev-redis
    restart: on-failure
    ports:
      - "6379:6379"
