name: matterchat-dev
services:
  postgres:
    image: postgres:18-alpine
    container_name: matterchat-dev-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:8-alpine
    container_name: matterchat-dev-redis
    restart: on-failure
    ports:
      - "6379:6379"

  livekit:
    image: livekit/livekit-server:latest
    container_name: matterchat-dev-livekit
    restart: on-failure
    ports:
      - "7880:7880"
      - "7881:7881/tcp"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml

